##
# Testing stuff
#
# @file Makefile
# @version 0.1 :3

OBJS = im_on_fire.cpp
CC = g++

#COMPILER_FLAGS specifies the additional compilation options we're using
# -w suppresses all warnings
# -Wall shows ALL warnings

COMPILER_FLAGS =
LINKER_FLAGS =
OBJ_NAME = a.out

lcg : jesse.cpp
	$(CC) $(COMPILER_FLAGS) -c jesse.cpp
	$(CC) jesse.o $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
# 	./(OBJ_NAME)
